image: python:3.7

stages:
  - static
  - prepare data
  - test

black:
  before_script:
    - pip install black
  stage: static
  script:
    - poetry run black --check ./

download cmapss:
  stage: prepare data
  before_script:

  script:
    - curl -o ./data https://ti.arc.nasa.gov/c/6/
  artifacts:
    paths:
      - ./data
    expire_in: 1 hour

unittest:
  stage: test
  before_script:
  - pip install poetry
  - poetry install
  script:
    - poetry run python -m unittest -v
  needs: ["download cmapss"]
