image: python:3.7

stages:
  - static
  - prepare data
  - test

black:
  stage: static
  before_script:
    - pip install black
  script:
    - black --check ./

flake8:
  stage: static
  before_script:
    - pip install flake8
  script:
    - flake8 ./tests ./rul_datasets

mypy:
  stage: static
  before_script:
    - pip install poetry
    - poetry install
  script:
    - mypy ./tests ./rul_datasets

download cmapss:
  stage: prepare data
  script:
    - curl -o ./data https://ti.arc.nasa.gov/c/6/
  artifacts:
    paths:
      - ./data
    expire_in: 1 hour

unittest:
  stage: test
  before_script:
    - pip install poetry
    - poetry install
  script:
    - poetry run python -m unittest -v
  needs: ["download cmapss"]
