[tool.poetry]
name = "rul_datasets"
version = "0.2.0"
description = "A collection of datasets for RUL estimation as Lightning Data Modules."
authors = ["Krokotsch, Tilman <tilman.krokotsch@iav.de>"]

[tool.poetry.dependencies]
python = "^3.7"
torch = "^1.9.0"
pytorch-lightning = "^1.4.4"
scikit-learn = "^0.24.2"
tqdm = "^4.62.2"

[tool.poetry.dev-dependencies]
black = {extras = ["d"], version = "^21.7b0"}
flake8 = "^3.9.2"
mypy = "^0.910"
hydra-core = "^1.1.1"

[tool.mypy]
plugins = "numpy.typing.mypy_plugin"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
