[tool.poetry]
name = "rul_datasets"
version = "0.1.0"
description = "A collection of datasets for RUL estimation as Lightning Data Modules."
authors = ["Krokotsch, Tilman (TP-T) <tilman.krokotsch@iav.de>"]

[tool.poetry.dependencies]
python = "^3.7"
torch = "^1.9.0"
pytorch-lightning = "0.10.0"
scikit-learn = "^0.24.2"

[tool.poetry.dev-dependencies]
black = "^21.7b0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
