name: Install Poetry
description: "Installs the requested version of poetry."
inputs:
  poetry-version:
    description: "version of poetry to install"
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v4
      with:
        cache: "poetry"
    - run: pipx install poetry==${{ inputs.poetry-version }}
      shell: "bash"
    - run: poetry install
      shell: "bash"